### ISSUE TITLE
Steps unclear when creating the 2nd Node (Node02)

### ISSUE THREAD

**Issue by thetoppy** [Azure/AzureStackHCI-EvalGuide#35]
Hi Team,

When creating the 1st Node (Node 01) the instruct mentioned to created 4 Disk of 100 GB there (Data01,Data02,Data03,Data04) 

1. It doesn't mention why we we need 4 disks here
2. When create the 2nd Node - do we need to repeat 4 Disks for Node02 as well? Data01.vhdx, Data02.vhdx and so on.

It is unclear in this steps.

The powershell - Copy and Paste doesnt seem to work.

Error:

Invoke-Command : Cannot validate argument on parameter 'VMName'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At line:1 char:24
+ Invoke-Command -VMName "$nodeName" -Credential $domainCreds -ScriptBl ...
+                        ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Command], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeCommandCommand

**Comment by mattmcspirit** [comment]
Hi - Yep, each of your nodes should have the 4 data disks.

When you get to the "repeat creation process", bounce back up to the top, specifically to the https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3b_AzSHCINodesPS.md#create-the-azshcinode01-vm-using-powershell stage, and run all the scripts again.  The only thing you need to adjust is the $nodeName = "AZSHCINODE01", which you'll find in a few places.  Simply change this to 02 instead of 01, and all should work fine. I chose to split up the scripts and explain a bit more about each one, so people would understand what's happening, however if you copy them all to a PowerShell ISE, you may find that easier.

If you make a mistake and want to recreate the VM, simply delete it from Hyper-V Manager, then navigate to C:\VMs and delete the folder that contains the VM you wish to delete.

Hope that helps.
