### ISSUE TITLE
Longer Term Deployment Options

### ISSUE THREAD

**Issue by liamfoneill** [Azure/AzureStackHCI-EvalGuide#54]
Not sure if what I want to do is even possible but let's say you have successfully completed the guide (following all of the instructions) and deployed the cluster with Hyper-V nested virtualisation. You will end up with 4 VMs, 
- 1 Domain Controller
-  1 Workstation Windows 10 VM
- 2 HCI Node VMs

They are connected to the NAT switch. You deploy your first VM on the Stack HCI cluster and you want to join it to the Domain (let's assume it is a secondary domain controller you are trying to deploy). As the only domain controller existing outside of the Stack Cluster I don't think it will be able to see the existing Domain controller. 

This might be impossible or it might a simple nested virtualisation/networking question but my mind is drawing a blank. The VMs are connected to an 'external' compute switch on the Stack HCI nodes but I don't think they will be able to see the Domain controller on the Nat switch on my top level hypervisor host  

How do I extend the existing domain into the cluster network where the VMs will be located?

**Comment by mattmcspirit** [comment]
Hi Liam,

Based on the nested config you've deployed in the guide, I actually think that any VMs running on your nested AzSHCI nodes, attached to the AzSHCI nodes "External" network vSwitch (which in turn is bound to the InternalNAT switch) _should_ be able to reach anything on your sandbox 192.168.0.0/24 network, including the AzSHCI nodes themselves (on the mgmt network) and the DC/WAC VMs. There's no reason why that shouldn't work from a network communication perspective.

The challenge however, is that you're then at multiple layers of nesting, so performance may be pretty bad at that point, but _should_ still work, assuming you can throw enough horsepower at the nested VM running on the AzSHCI cluster.

This is primarily the reason i just walked people through deploying an "empty" VM rather than one with an OS, but networking should work fine.

Let me know! :)

**Comment by liamfoneill** [comment]
Thanks I will have another poke around later on. I'm not too concerned with performance as I just intend to have a few VMs running for demoing etc... at least this will give my 16-core 5950x something to actually do :)

**Comment by mattmcspirit** [comment]
Cool - screenshots please, or it didn't happen! :)

**Comment by liamfoneill** [comment]
![image](https://user-images.githubusercontent.com/1243172/107677797-8eb23200-6c92-11eb-90a2-d4c9b8eed4da.png)

I definitely happened and my poor bank statement backs it up!
