### ISSUE TITLE
Missing Hyper-V-PowerShell in AzSHCINodes

### ISSUE THREAD

**Issue by paracetamol32** [Azure/AzureStackHCI-EvalGuide#8]
In WAC wizard vmswitch failed because Hyper-V-PowerShell module  is not installed on each nodes.

**Comment by mattmcspirit** [comment]
Thanks - we'll look into this and update when we know more.  WAC should install the PS modules early in the cluster creation wizard.

**Comment by mattmcspirit** [comment]
This one is on me - run the following from your Hyper-V host:

```powershell
# Provide the domain credentials to log into the VM
$domainName = "azshci.local"
$domainAdmin = "$domainName\labadmin"
$domainCreds = Get-Credential -UserName "$domainAdmin" -Message "Enter the password for the LabAdmin account"
# Define node name
$nodeName = "AZSHCINODE01"
Invoke-Command -VMName "$nodeName" -Credential $domainCreds -ScriptBlock {
    # Enable the Hyper-V role within the Azure Stack HCI OS
    Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V,RSAT-Hyper-V-Tools-Feature,Microsoft-Hyper-V-Management-PowerShell
}
```

Adjust the $nodeName to apply to the different nodes.

**Comment by kongou-ae** [comment]
I encountered the same issue in a nested Azure Stack HCI on Azure VM. My solution is to run "Enable-WindowsOptionalFeature -Online -FeatureName  Microsoft-Hyper-V-Management-PowerShell" in the Azure Stack HCI OS.

**Comment by mattmcspirit** [comment]
Closing this for now, as it's been fixed in the steps here: https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3a_AzSHCINodesGUI.md#enable-the-hyper-v-role-on-your-azure-stack-hci-node and in the PowerShell steps here: https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/nested/steps/3b_AzSHCINodesPS.md#enable-the-hyper-v-role-on-your-azure-stack-hci-node
