### ISSUE TITLE
Unable to register cluster to Azure

### ISSUE THREAD

**Issue by nicolgit** [Azure/AzureStackHCI-EvalGuide#94]
I am registering my cluster EvalGuide to azure following the instructions found here via Windows Admin Center <https://github.com/Azure/AzureStackHCI-EvalGuide/blob/main/deployment/steps/3_AzSHCIIntegration.md> 

I am receiving the following error: 

`Failed to register with Azure for cluster: azstackcluster.contoso.com. Error: RemoteException: Failed to register. Couldn't generate self-signed certificate on node(s) AzSHOST1,AzSHOST2,AzSHOST1,AzSHOST2. Couldn't set and verify registration certificate on node(s) AzSHOST1,AzSHOST2,AzSHOST1,AzSHOST2. Make sure every clustered node is up and has Internet connectivity (at least outbound to Azure).`

I'm quite new on HCI so I don't know where to start... any advice?
N

**Comment by mgodfre3** [comment]
This issue is not with the deployment process or the scripts used to deploy the EvalGuide, but with the registration process after. Please troubleshoot the registration process and connection to Azure, https://docs.microsoft.com/en-us/azure-stack/hci/deploy/troubleshoot-hci-registration .

Closing issue.
